export default {
  data: [
    {
      id: 1,
      first_name: "Erme",
      last_name: "Schultz",
      cellphone: "(41) 99999-9999",
      email: "erme@email.com",
      company: "Commcepta",
      title: "Developer",
      street: "Street number 1",
      city: "Curitiba",
      state: "Paraná",
    },
    {
      id: 2,
      first_name: "Suzane",
      last_name: "Machado",
      cellphone: "(41) 99999-9999",
      email: "suzane@email.com",
      company: "Commcepta",
      title: "IT Head",
      street: "Street number 1",
      city: "Curitiba",
      state: "Paraná",
    },
    {
      id: 3,
      first_name: "Thais",
      last_name: "Guisi",
      cellphone: "(41) 99999-9999",
      email: "thais@email.com",
      company: "Commcepta",
      title: "Relationship Assistant",
      street: "Street number 1",
      city: "Curitiba",
      state: "Paraná",
    },
  ],
};
